module: dagster
environment: generic
replicas: 1

containers:
 # name: dagster
 # image: ghcr.io/miletocarmelo/devpos_helm_generic_dagster_backend/dagster
 # tags: latest
 ports:
   containerPort: 3000
 resources:
   requests:
     memory: "256Mi"
     cpu: "100m"
   limits:
     memory: "512Mi" 
     cpu: "200m"

service:
 type: ClusterIP
 port: 3000
 targetPort: 3000