# values.yaml
module: dagster
environment: generic
replicaCount: 1
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000 
image:
  repository: dagster/dagster-celery-k8s
  pullPolicy: IfNotPresent
  tag: "latest"
container:
  port: 3000
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
  spec:
    path: /
