apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-storage
  namespace: {{ .Values.module }}-{{ .Values.environment }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}