# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  namespace: {{ .Values.module }}-{{ .Values.environment }}
  labels:
    app.kubernetes.io/instance: {{ .Values.module }}-{{ .Values.environment }}
data:
  workspace.yaml: ""  # Laissé vide intentionnellement