apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  namespace: {{ .Values.module }}-{{ .Values.environment }}
  labels:
    app.kubernetes.io/instance: {{ .Values.module }}-{{ .Values.environment }}
data:
  workspace.yaml: |
    load_from:
      - grpc_server:
          host: pipeline-successtest
          port: 4000
          location_name: "pipeline-successtest"